DROP TABLE CONTACT_TBL; 
CREATE TABLE CONTACT_TBL( 
	CONTACT_NO NUMBER NOT NULL,
	NAME VARCHAR2(20 BYTE) NOT NULL,
	TEL VARCHAR2(20 BYTE),
	EMAIL VARCHAR2(99 BYTE),
	ADDRESS VARCHAR2(99 BYTE)
);

ALTER TABLE CONTACT_TBL
	ADD CONSTRAINT PK_CONTACT PRIMARY KEY(CONTACT_NO);

DROP SEQUENCE CONTACT_SEQ; 
CREATE SEQUENCE CONTACT_SEQ NOCACHE;
INSERT INTO CONTACT_TBL(CONTACT_NO, NAME, TEL, EMAIL, ADDRESS) VALUES(CONTACT_SEQ.NEXTVAL, '정숙', '010-111-1111', 'DOON@NAVER.COM', '서울');
INSERT INTO CONTACT_TBL(CONTACT_NO, NAME, TEL, EMAIL, ADDRESS) VALUES(CONTACT_SEQ.NEXTVAL, '미정', '010-222-2222', 'MOON@NAVER.COM', '경기');
INSERT INTO CONTACT_TBL(CONTACT_NO, NAME, TEL, EMAIL, ADDRESS) VALUES(CONTACT_SEQ.NEXTVAL, '정숙', '010-333-3333', 'EEAD@NAVER.COM', '서울');

SELECT CONTACT_NO, NAME, TEL, EMAIL, ADDRESS
  FROM CONTACT_TBL;
